spring.application.name=lightlife

spring.datasource.url=jdbc:postgresql://localhost:5432/akif
spring.datasource.username=postgres
spring.datasource.password=1461

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=lightlife
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Security test ortamı için kapalı gibi davran
spring.security.filter.dispatcher-types=async,error,request
