spring.application.name=lightlife

spring.datasource.url=jdbc:postgresql://localhost:5432/akif
spring.datasource.username=postgres
spring.datasource.password=Nisa%ym9444

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=lightlife
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.web.servlet.resource.ResourceHttpRequestHandler=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR

spring.security.filter.dispatcher-types=async,error,request
